steps:
  - name: Hello world action
    with: # Set the secret as an input
      super_secret: ${{ secrets.API_KEY }}
    env: # Or as an environment variable
      super_secret: ${{ secrets.API_KEY }}
